version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
    - JVM_OPTS: -Xmx3200m
    - TERM: dumb
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "build.gradle" }}
        - v1-dependencies-
    - run: gradle dependencies
    - save_cache:
        paths:
        - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}
    - run: 
    name: "Build and Publish Release on GitHub"
          command: |
            NOW="$(date)" 
            ZIP_FILE_NAME=CounterCI
            TAG=Release-$(date '+%Y-%m-%d-%H-%M-%S')
            cd CounterCI
            gradle jar
            cd ./build/libs/
            zip ${ZIP_FILE_NAME}.zip CounterCI.jar 
            github-release upload --token ${GITHUB_TOKEN} --owner ${PROJECT_USERNAME} --repo ${PROJECT_REPONAME} --tag ${TAG} --name ${TAG} --body "Release date: ${NOW}" ${ZIP_FILE_NAME}.zip
  workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master 
